[[redirects]]
  from = "/addressService/*"
  to = "http://139.180.147.199:8082/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/accountService/*"
  to = "https://accounts.nika.guru/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/coinPriceService/*"
  to = "https://coinsprices.nika.guru/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/mailService/*"
  to = "https://mail.nika.guru/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/log/*"
  to = "https://monitor.nika.guru/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}